apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-app.fullname" . }}-config
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
data:
  FLASK_ENV: {{ .Values.configMap.env | quote }}
  LOG_LEVEL: {{ .Values.configMap.logLevel | quote }}
